"""Improved build script:
- Stores resources as raw bytes (no base64 4/3 expansion).
- Verifies UPX availability before invoking PyInstaller (saves time on failure).
- Supports --onedir mode (faster startup, smaller total distribution).
- Excludes unused heavy modules to shrink the bundle.
- Uses logging instead of print.
"""
import argparse
import base64
import logging
import shutil
import subprocess
import sys
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="[%(levelname)s] %(message)s")
log = logging.getLogger("build")

# Modules that PyInstaller pulls in by default but we never use. Excluding them
# can shave several MB off the bundle (especially in --onefile mode).
EXCLUDED_MODULES = [
    "matplotlib", "scipy", "pandas", "PyQt5", "PyQt6", "PySide2", "PySide6",
    "IPython", "jedi", "pytest", "sphinx", "notebook", "pytest_asyncio",
    "tornado", "zmq", "IPython.utils.traitlets", "unittest",
    "librosa", "sklearn", "sympy", "pydoc", "doctest",
]


def create_resources_file() -> bool:
    """Embed image resources as raw bytes into resources.py.

    Switching from base64 to a bytes literal removes the 33% expansion; for a
    92 KB icon this saves about 30 KB of .pyc size. Returns True if the
    resulting file differs from disk (i.e. a rebuild is warranted).
    """
    candidates = [Path("cym_icon.ico"), Path("jili.jpg"), Path("jili.png")]
    pic_dir = Path("picture")
    if pic_dir.is_dir():
        for p in pic_dir.iterdir():
            if p.suffix.lower() in (".png", ".jpg", ".jpeg", ".bmp", ".ico"):
                candidates.append(p)

    resources = {}
    for p in candidates:
        if not p.is_file():
            continue
        try:
            resources[p.name] = p.read_bytes()
            log.info("embedded resource: %s (%d bytes)", p, len(resources[p.name]))
        except OSError as e:
            log.warning("failed to read %s: %s", p, e)

    lines = [
        "# Auto-generated by build.py. Do not edit by hand.",
        "RESOURCES = {",
    ]
    for name, data in resources.items():
        # repr() of bytes yields a valid b"..." literal that the parser re-loads
        # as the original bytes object -- no decode/encode round trip.
        lines.append(f"    {name!r}: {data!r},")
    lines.append("}")
    lines.append("")
    lines.append("")
    lines.append("def get(name):")
    lines.append('    """Return the raw bytes of an embedded resource, or None."""')
    lines.append("    return RESOURCES.get(name)")

    new_text = "\n".join(lines) + "\n"
    out = Path("resources.py")
    if out.exists() and out.read_text(encoding="utf-8") == new_text:
        log.info("resources.py is up to date; no rewrite needed")
        return False
    out.write_text(new_text, encoding="utf-8")
    log.info("wrote resources.py (%d bytes total)", len(new_text))
    return True


def _format_excludes_for_spec() -> str:
    return ", ".join(f'"{m}"' for m in EXCLUDED_MODULES)


def create_spec_file(onefile: bool) -> None:
    """Write PyInstaller .spec file tailored to this project."""
    upx_flag = _check_upx()
    spec = f"""# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by build.py

block_cipher = None

a = Analysis(
    ['CC.py'],
    pathex=[],
    binaries=[],
    # No 'datas': cym_icon.ico is embedded into resources.py so we don't
    # need a separate on-disk copy in the bundle.
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=[{_format_excludes_for_spec()}],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='CC',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx={upx_flag},
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # GUI app
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
{"COLLECT = COLLECT(exe, a.datas, strip=False, upx=" + str(upx_flag) + ", name='CC')" if not onefile else ""}
)
"""
    Path("CC.spec").write_text(spec, encoding="utf-8")


def _check_upx() -> bool:
    """Return True if UPX is available on PATH, else False (with a warning)."""
    if shutil.which("upx") is None:
        log.warning("UPX not found on PATH; bundle will not be compressed "
                    "(install UPX from https://upx.github.io/ for ~30%% size reduction)")
        return False
    return True


def build_executable() -> bool:
    log.info("running PyInstaller...")
    try:
        subprocess.check_call([sys.executable, "-m", "PyInstaller", "--clean", "CC.spec"])
    except subprocess.CalledProcessError as e:
        log.error("PyInstaller failed: %s", e)
        return False
    log.info("build complete")
    return True


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Build the image-to-font tool")
    p.add_argument("--onedir", action="store_true",
                   help="produce a directory bundle instead of a single exe "
                        "(faster startup, easier to debug, easier to ship updates)")
    return p.parse_args()


def main() -> int:
    args = parse_args()
    log.info("building (mode=%s)", "onedir" if args.onedir else "onefile")
    create_resources_file()
    create_spec_file(onefile=not args.onedir)
    return 0 if build_executable() else 1


if __name__ == "__main__":
    sys.exit(main())
